FROM golang:1.25-alpine AS builder

ARG VERSION=0.68.1
ARG COMMIT=unknown
ARG BUILD_DATE=unknown

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -checklinkname=0 -X github.com/fatedier/frp/pkg/util/version.version=${VERSION} -X github.com/fatedier/frp/pkg/util/version.commit=${COMMIT} -X github.com/fatedier/frp/pkg/util/version.buildDate=${BUILD_DATE}" -tags "frpc,noweb" -o /app/frpc ./cmd/frpc

FROM alpine:3.20

LABEL maintainer="MoFrp <support@mofrp.moiu.cn>"

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/frpc /usr/bin/frpc
COPY conf/frpc.toml /etc/frp/frpc.toml

ENTRYPOINT ["/usr/bin/frpc"]
CMD ["-c", "/etc/frp/frpc.toml"]
